export const LOADING_START = "LOADING_START"
export const LOADING_STOP = "LOADING_STOP"

export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const SIGN_UP = "SIGN_UP"

export const CREATE_POST = "CREATE_POST"
export const GET_OWN_POSTS = "GET_OWN_POSTS"
export const GET_SINGLE_POST = "GET_SINGLE_POST"
export const GET_ALL_POSTS = "GET_ALL_POSTS"
export const LIKE_UNLIKE_POST = "LIKE_UNLIKE_POST"

export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_USER_POSTS = "GET_USER_POSTS"
export const GET_USER_SCORE = "GET_USER_SCORE"
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS"

export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS"

export const CREATE_GROUP = "CREATE_GROUP"
export const GET_OWN_GROUPS = "GET_OWN_GROUPS"

export const CREATE_MESSAGE = "CREATE_MESSAGE"
